apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jppp5k9e2-nodejs 
  janus-idp.io/tekton: jppp5k9e2-nodejs
  backstage.io/kubernetes-id: jppp5k9e2-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jppp5k9e2-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  